class_name IntentErrorCodes extends RefCounted

const INSUFFICIENT_FUNDS := "INSUFFICIENT_FUNDS"
const INSUFFICIENT_CARGO := "INSUFFICIENT_CARGO"
const INVALID_STATE := "INVALID_STATE"
const CUSTOMS_BLOCKED := "CUSTOMS_BLOCKED"
const NO_HANDLER := "NO_HANDLER"
const VALIDATION_ERROR := "VALIDATION_ERROR"
const HANDLER_ERROR := "HANDLER_ERROR"
const DUPLICATE_INTENT := "DUPLICATE_INTENT"
const TRANSACTION_FAILED := "TRANSACTION_FAILED"